version: "3.6"
services:
  webhook2mqtt:
    build: .
    restart: always
#    ports:
#      - "127.0.0.1:5058:80"
#    dns_search: lan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
     TZ: "Europe/Berlin"
     MQTT_SERVER: 'home.jru.me'
     MQTT_PORT: 1883
     MQTT_PATH: 'webhook'
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netatmo_jru_me_http.entrypoints=web"
      - "traefik.http.routers.netatmo_jru_me_http.rule=Host(`netatmo.jru.me`)"
#      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.netatmo_jru_me_http.middlewares=https_redirect"
      - "traefik.http.routers.netatmo_jru_me.entrypoints=websecure"
      - "traefik.http.routers.netatmo_jru_me.rule=Host(`netatmo.jru.me`)"
      - "traefik.http.routers.netatmo_jru_me.tls=true"
      - "traefik.http.routers.netatmo_jru_me.tls.certresolver=my_certresolver"
    restart: always
    logging:
      driver: syslog

networks:
  traefik_proxy:
    name: traefik
    external: true
