services:
  webhook2mqtt:
    build: .
    restart: always
# adapt to your needs
#    ports:
#      - "127.0.0.1:5058:80"
#    dns_search: lan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      TZ: ${TZ:-Europe/Berlin}
      MQTT_SERVER: ${MQTT_SERVER}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_PATH: ${MQTT_PATH:-webhook}
      # MQTT_USER: ${MQTT_USER}
      # MQTT_PASSWORD: ${MQTT_PASSWORD}
      # MQTT_TLS: ${MQTT_TLS:-false}
      # WEBHOOK_TOKEN: ${WEBHOOK_TOKEN}
# example config for https with traefik
#    networks:
#      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook2mqtt_router_http.entrypoints=web"
      - "traefik.http.routers.webhook2mqtt_router_http.rule=Host(`${WEBHOOK_HOST}`)"
#      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.webhook2mqtt_router_http.middlewares=https_redirect"
      - "traefik.http.routers.webhook2mqtt_router.entrypoints=websecure"
      - "traefik.http.routers.webhook2mqtt_router.rule=Host(`${WEBHOOK_HOST}`)"
      - "traefik.http.routers.webhook2mqtt_router.tls=true"
      - "traefik.http.routers.webhook2mqtt_router.tls.certresolver=my_certresolver"
# log to syslog | optional
    logging:
      driver: syslog

#networks:
#  traefik_proxy:
#    name: traefik
#    external: true
