version: "3.3"
services:
  webhook2mqtt:
    build: .
    restart: always
    ports:
      - "127.0.0.1:5058:80"
    dns_search: lan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
     TZ: "Europe/Berlin"
     MQTT_SERVER: '192.168.176.6'
     MQTT_PORT: 1883
     MQTT_PATH: 'webhook'
