version: "3.6"
services:
  webhook2mqtt:
    build: .
    restart: always
# adapt to your needs
#    ports:
#      - "127.0.0.1:5058:80"
#    dns_search: lan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
     TZ: "Europe/Berlin"
     MQTT_SERVER: 'home.jru.me'
     MQTT_PORT: 1883
     MQTT_PATH: 'homeassistant/webhook'
# example config for https with traefik
#    networks:
#      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook2mqtt_router_http.entrypoints=web"
      - "traefik.http.routers.webhook2mqtt_router_http.rule=Host(`netatmo.jru.me`)"
#      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.webhook2mqtt_router_http.middlewares=https_redirect"
      - "traefik.http.routers.webhook2mqtt_router.entrypoints=websecure"
      - "traefik.http.routers.webhook2mqtt_router.rule=Host(`netatmo.jru.me`)"
      - "traefik.http.routers.webhook2mqtt_router.tls=true"
      - "traefik.http.routers.webhook2mqtt_router.tls.certresolver=my_certresolver"
    restart: always
# log to syslog | optional
    logging:
      driver: syslog

#networks:
#  traefik_proxy:
#    name: traefik
#    external: true
